FROM php:8.2-apache

#  Añadir Composer
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

# Habilitar mod_rewrite (Symfony lo necesita)
RUN a2enmod rewrite

# Apuntar Apache al directorio public de Symfony
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf

WORKDIR /var/www/html
