security:
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            security: false

    access_control:
        - { path: ^/api/admin, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }