# Usamos una imagen ligera de Python
FROM python:3.11-slim

# Directorio de trabajo
WORKDIR /app

# Copiamos los requisitos e instalamos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto del código
COPY . .

# Exponemos el puerto de FastAPI
EXPOSE 5000

# Comando para ejecutar la app con "hot reload" para que sea fácil desarrollar
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]